;Default Sizes
DEFAULT_WND_WIDTH equ 800
DEFAULT_WND_HEIGHT equ 600
MIN_WND_WIDTH  equ 480
MIN_WND_HEIGHT equ 360

;Menu
IDM_FILE_SAVE equ 103h
IDM_FILE_EXIT equ 109h
IDM_HELP_ABOUT equ 901h

;Status Bar
STATUS_BAR_PARTS equ 9


