; Listing generated by Microsoft (R) Optimizing Compiler Version 19.38.33133.0 

include listing.inc

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	??0VERTEX@@QEAA@MMMMMM@Z			; VERTEX::VERTEX
PUBLIC	??1VERTEX@@QEAA@XZ				; VERTEX::~VERTEX
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	_fltused:DWORD
pdata	SEGMENT
$pdata$??0VERTEX@@QEAA@MMMMMM@Z DD imagerel $LN3
	DD	imagerel $LN3+138
	DD	imagerel $unwind$??0VERTEX@@QEAA@MMMMMM@Z
$pdata$??1VERTEX@@QEAA@XZ DD imagerel $LN3
	DD	imagerel $LN3+8
	DD	imagerel $unwind$??1VERTEX@@QEAA@XZ
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
xdata	SEGMENT
$unwind$??0VERTEX@@QEAA@MMMMMM@Z DD 011801H
	DD	07018H
$unwind$??1VERTEX@@QEAA@XZ DD 010601H
	DD	07006H
xdata	ENDS
; Function compile flags: /Odtp /RTCsu
_TEXT	SEGMENT
this$ = 16
??1VERTEX@@QEAA@XZ PROC					; VERTEX::~VERTEX
; File D:\dev\cpp\40_BIM\01_AlanBaylis\cpp\OGLMDI2_VS2022\Build01\vertex.cpp
; Line 19
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
; Line 20
	pop	rdi
	ret	0
??1VERTEX@@QEAA@XZ ENDP					; VERTEX::~VERTEX
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
_TEXT	SEGMENT
this$ = 16
sx$ = 24
sy$ = 32
sz$ = 40
snx$ = 48
sny$ = 56
snz$ = 64
??0VERTEX@@QEAA@MMMMMM@Z PROC				; VERTEX::VERTEX
; File D:\dev\cpp\40_BIM\01_AlanBaylis\cpp\OGLMDI2_VS2022\Build01\vertex.cpp
; Line 15
$LN3:
	movss	DWORD PTR [rsp+32], xmm3
	movss	DWORD PTR [rsp+24], xmm2
	movss	DWORD PTR [rsp+16], xmm1
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
; Line 14
	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax], 3
; Line 8
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR sx$[rsp]
	movss	DWORD PTR [rax+4], xmm0
; Line 9
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR sy$[rsp]
	movss	DWORD PTR [rax+8], xmm0
; Line 10
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR sz$[rsp]
	movss	DWORD PTR [rax+12], xmm0
; Line 11
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR snx$[rsp]
	movss	DWORD PTR [rax+16], xmm0
; Line 12
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR sny$[rsp]
	movss	DWORD PTR [rax+20], xmm0
; Line 13
	mov	rax, QWORD PTR this$[rsp]
	movss	xmm0, DWORD PTR snz$[rsp]
	movss	DWORD PTR [rax+24], xmm0
; Line 16
	mov	rax, QWORD PTR this$[rsp]
	pop	rdi
	ret	0
??0VERTEX@@QEAA@MMMMMM@Z ENDP				; VERTEX::VERTEX
_TEXT	ENDS
END
