;Position of SubMenus in Menus
 MENU_POS_INIT equ 0 ;Position of SubMenu in MenuInit = 0
 MENU_POS_CHILD00 equ 1 ;Position of SubMenu in MenuChild00 = 1
 MENU_POS_CHILD01 equ 2 ;Position of SubMenu in MenuChild01 = 2
 MENU_POS_CHILD06 equ 1 ;Position of SubMenu in MenuChild06 = 1

;File
 IDM_NEW_CHILD00 equ 10
 IDM_NEW_CHILD01 equ 11
 IDM_NEW_CHILD06 equ 16
 IDM_CLOSE equ 90
 IDM_EXIT equ 91

;Color
 IDM_BLACK equ 30
 IDM_RED equ 31
 IDM_GREEN equ 32
 IDM_BLUE equ 33
 IDM_WHITE equ 34

;Window
 IDM_TILE equ 80
 IDM_CASCADE equ 81
 IDM_ARRANGE equ 82
 IDM_CLOSEALL equ 99

;Help
 IDM_ABOUT equ 70

;First Child
 IDM_FIRSTCHILD equ 100

;Added during translation into MASM
 MdiMenuInit equ 40
 MdiMenuChild00 equ 50
 MdiMenuChild01 equ 51
 MdiMenuChild06 equ 56
 MdiAccel equ 60
