createVkContext proc
PROLOG 100h

call enumInstanceLayerProps
call checkValidationLayer
call enumInstanceExtensionProps
call checkDebugUtilsExt
call checkKhrSurfaceExt
call checkKhrWin32SurfaceExt

call createVkInstance
call createDebugMessenger
call createSurface
call enumPhysicalDevices
call selectPhysicalDevice
call getQueueFamilyProperties
call selectQueueFamily
call getCapabilities
call getFormats
call choosePresentMode
call createDevice
call createSwapchain
call createImageViews
call createRenderPass
call createShaderModules
call createPipelineLayout
call createGraphicsPipeline
call createCommandPool
call allocateCommandBuffers
call createSemaphores
call createFence
call createFrameBuffers
call recordCommandBuffers

leave
ret
createVkContext endp



destroyVkContext proc
PROLOG 100h

call destroyFrameBuffers
call destroyFence
call destroySemaphores
call destroyFrameBuffers
call destroyCommandPool
call destroyGraphicsPipeline
call destroyPipelineLayout
call destroyShaderModules
call destroyRenderPass
call destroyImageViews
call destroySwapchain
call destroyDevice
call destroySurface
call destroyDebugMessenger
call destroyVkInstance

leave
ret
destroyVkContext endp
